// corpus for photographer name list
// convert to JSON?
/*
* corpus sources:
* https://en.wikipedia.org/wiki/List_of_women_photographers
* https://en.wikipedia.org/wiki/List_of_photographers
* https://en.wikipedia.org/wiki/List_of_photojournalists
* https://en.wikipedia.org/wiki/List_of_street_photographers
* http://spacescorners.com/books_byartist.html
*/
module.exports =

  [
    "Fadil Berisha",
    "Gjon Mili",
    "Gustavo Aguerre",
    "Horacio Coppola",
    "Sara Facio",
    "Esteban Gonnet",
    "Luis Graham-Yooll",
    "Annemarie Heinrich",
    "Alejandro Kuropatwa",
    "Adriana Lestido",
    "Grete Stern",
    "Sergio Castiglione",
    "David Adams",
    "Jack Atley",
    "Daniel Berehulak",
    "Harold Cazneaux",
    "Neville Coleman",
    "Peter Dombrovskis",
    "Ken Duncan",
    "Max Dupain",
    "Adam Ferguson",
    "Bill Henson",
    "Graham Howe",
    "Frank Hurley",
    "Russell James",
    "Barry Kay",
    "Charles Kerry",
    "Peter Lik",
    "Darryn Lyons",
    "Charles Page",
    "Trent Parke",
    "Wolfgang Sievers",
    "Steven Siewert",
    "Andrew Stark",
    "Olegas Truchanas",
    "Ian Wallace",
    "Anne Zahalka",
    "Manfred Baumann",
    "Lukas Beck",
    "Andreas Bitesnich",
    "Wilhelm J. Burger",
    "Ernst Haas",
    "Gottfried Helnwein",
    "Josef Hoflehner",
    "Lisette Model",
    "Inge Morath",
    "Willy Puchner",
    "Baron Raimund von Stillfried",
    "Stillfried & Andersen",
    "Rena Effendi",
    "GMB Akash",
    "Shahidul Alam",
    "Manzur Alam Beg",
    "Munem Wasif",
    "Jean-Marie Bottequin",
    "Isidore Jacques Eggermont",
    "Martine Franck",
    "Harry Gruyaert",
    "Carl de Keyzer",
    "Eugene Lemaire",
    "Marcel Mariën",
    "Filip Naudts",
    "Mayeul Akpovi",
    "Marc Ferrez",
    "Vik Muniz",
    "Arthur Omar",
    "Sebastião Salgado",
    "Cássio Vasconcellos",
    "Guy Veloso",
    "Dith Pran",
    "Bryan Adams",
    "Roy Arden",
    "Melissa Auf der Maur",
    "George Barker",
    "Roloff Beny",
    "Edward Burtynsky",
    "Geneviève Cadieux",
    "Paul Couvrette",
    "Julie Doiron",
    "Yousuf Karsh",
    "Koby",
    "Paul Labonté",
    "R. Ian Lloyd",
    "Arnaud Maggs",
    "Raphael Mazzucco",
    "Jo-Anne McArthur",
    "Julie Moos",
    "Freeman Patterson",
    "Bob Peterson",
    "Peter Pitseolak",
    "Robert Polidori",
    "Raymond Henry St. Arnaud",
    "Floria Sigismondi",
    "Sam Tata",
    "Larry Towell",
    "Jeff Wall",
    "Donald Weber (photographer)",
    "Brian Wood",
    "Ricardo Carrasco",
    "Jesús Inostroza",
    "Carlos Reyes-Manzo",
    "Hong Cheong",
    "Tong Cheong",
    "Sun-chang Lo",
    "Zhang Xiao",
    "Miguel Gómez",
    "Joseph Makula",
    "Luis Castaneda",
    "Alberto Korda",
    "Karel Cudlín",
    "František Drtikol",
    "Rudolf Koppitz",
    "Josef Koudelka",
    "Antonín Kratochvíl",
    "Rudolf Franz Lehnert",
    "Markéta Luskačová",
    "Frank Plicka",
    "Karel Plicka",
    "Jan Saudek",
    "Ignác Šechtl",
    "Josef Jindřich Šechtl",
    "Marie Šechtlová",
    "Jindřich Štreit",
    "Josef Sudek",
    "Miroslav Tichý",
    "Josef Větrovský",
    "Mads Alstrup",
    "Per Bak Jensen",
    "Reg Balch",
    "Morten Bo",
    "Krass Clement",
    "Joakim Eskildsen",
    "Frederikke Federspiel",
    "Kristen Feilberg",
    "Jens Fink-Jensen",
    "Jan Grarup",
    "Ludvig Grundtvig",
    "Georg Emil Hansen",
    "Keld Helmer-Petersen",
    "Jacob Holdt",
    "Jesper Høm",
    "Kirsten Klein",
    "Astrid Kruse Jensen",
    "Claus Bjørn Larsen",
    "Erling Mandelmann",
    "Anton Melbye",
    "Rigmor Mydtskov",
    "Jacob Riis",
    "Viggo Rivad",
    "Leif Schiller",
    "Lars Schwander",
    "Jacob Aue Sobol",
    "Mary Steen",
    "Rudolph Striegler",
    "Mathias Vestergaard",
    "Sigvart Werner",
    "Mary Willumsen",
    "Hugo Cifuentes",
    "Ayman Lotfy",
    "Sherif Sonbol",
    "Alexander Gronsky",
    "Johannes Pääsuke",
    "Jakob Sildnik",
    "Ismo Hölttö",
    "Sirkka-Liisa Konttinen",
    "Santeri Levas",
    "Olympe Aguado",
    "Hippolyte Arnoux",
    "Yann Arthus-Bertrand",
    "Eugène Atget",
    "Alan Aubry",
    "Edouard Baldus",
    "Bruno Barbey",
    "Jean Baudrillard",
    "Hippolyte Bayard",
    "Auguste-Rosalie Bisson",
    "Louis Désiré Blanquart-Evrard",
    "Félix Bonfils",
    "Edouard Boubat",
    "Alexandra Boulat",
    "Jacques Bourboulon",
    "Jean-Christian Bourcart",
    "Guy Bourdin",
    "Bruno Braquehais",
    "Brassaï",
    "Adolphe Braun",
    "Serge Brunier",
    "Jean-Marc Bustamante",
    "Bernard Cahier",
    "Claude Cahun",
    "Sophie Calle",
    "Henri Cartier-Bresson",
    "Jean Chamoux",
    "Jean-Philippe Charbonnier",
    "Désiré Charnay",
    "Antoine Claudet",
    "Paul de Cordon",
    "Jules Gervais-Courtellemont",
    "Louis-Jacques-Mandé Daguerre",
    "Luc Delahaye",
    "Patrick Demarchelier",
    "André-Adolphe-Eugène Disdéri",
    "Robert Doisneau",
    "Maxime Du Camp",
    "Pierre Dubreuil",
    "Jean Louis Marie Eugène Durieu",
    "Bruno Fabien",
    "Antoine Fauchery",
    "Bernard Faucon",
    "Hércules Florence",
    "Fernand Fonssagrives",
    "Auguste François",
    "Léon Gimpel",
    "Joseph-Philibert Girault de Prangey",
    "André Giroux",
    "Yohann Gozard",
    "Olivier Grunewald",
    "Emile Gsell",
    "Henri Huet",
    "Jules Itier",
    "Gaspard-Pierre-Gustave Joly de Lotbinière",
    "Jacques Henri Lartigue",
    "Louis Legrand",
    "Gustave Le Gray",
    "Henri Le Secq",
    "Auguste and Louis Lumière",
    "Serge Lutens",
    "Benedicte Van der Maar",
    "Pascal Meunier",
    "Jean-Baptiste Mondino",
    "Nadar",
    "Nicéphore Niépce",
    "Gilles Peress",
    "Constant Puyo",
    "Gérard Rancinan",
    "Henri-Victor Regnault",
    "Bettina Rheims",
    "Marc Riboud",
    "Willy Ronis",
    "Stéphane Sednaoui",
    "Jeanloup Sieff",
    "Camille Silvy",
    "Hedi Slimane",
    "Albert Spaggiari",
    "Christine Spengler",
    "Natalia Turine",
    "Franck Vogel",
    "Irakly Shanidze",
    "Christian von Alvensleben",
    "Dieter Appelt",
    "Thomas Bak",
    "Walter Ballhause",
    "Uta Barth",
    "Ingeborg de Beausacq",
    "Hilla Becher",
    "Bernd and Hilla Becher",
    "Hans Bellmer",
    "Henning von Berg",
    "Sibylle Bergemann",
    "Ruth Bernhard",
    "Peter Bialobrzeski",
    "Karl Blossfeldt",
    "Anna and Bernhard Blume",
    "Max Burchartz",
    "Peter Cornelius",
    "Thomas Dworzak",
    "Franz Fiedler",
    "Helmut Gernsheim",
    "Wilhelm von Gloeden",
    "Andreas Gursky",
    "John Gutmann",
    "Peter Guttman",
    "Esther Haase",
    "Siegfried Hansen",
    "Harald Hauswald",
    "John Heartfield",
    "Fritz Henle",
    "Ulrich Hensel",
    "Hannah Höch",
    "Heinrich Hoffmann",
    "Lotte Jacobi",
    "Clemens Kalischer",
    "Heinrich Kühn",
    "Karl Lagerfeld",
    "Ernst Heinrich Landrock",
    "Hans G. Lehmann",
    "Peter Leibing",
    "Esther Levine",
    "Peter Lindbergh",
    "Herbert List",
    "Loretta Lux",
    "Willy Matheisl",
    "Adolf de Meyer",
    "Hans Namuth",
    "Helmut Newton",
    "Anja Niedringhaus",
    "Guglielmo Plüschow",
    "Michael Poliza",
    "Albert Renger-Patzsch",
    "Leni Riefenstahl",
    "Michael Ruetz",
    "Thomas Ruff",
    "Erich Salomon",
    "August Sander",
    "Thyra Schmidt",
    "Stefanie Schneider",
    "Katharina Sieverding",
    "Giorgio Sommer",
    "Thomas Struth",
    "Gerda Taro (Gerta Pohorylle)",
    "Juergen Teller",
    "Peter Thomann",
    "Wolfgang Tillmans",
    "Herbert Tobias",
    "Heinrich Tønnies",
    "Ellen von Unwerth",
    "Chris von Wangenheim",
    "Charles Paul Wilp",
    "Michael Wolf",
    "Otto Wunderlich",
    "Nikos Economopoulos",
    "Tzeli Hadjidimitriou",
    "Yannis Kontos",
    "Vassilis Makris",
    "Lucas Samaras",
    "Basil Pao",
    "Ho Fan",
    "Brassaï",
    "Cornell Capa",
    "Robert Capa",
    "Zoltán Glass",
    "Lucien Hervé",
    "André Kertész",
    "László Moholy-Nagy",
    "Martin Munkácsi",
    "Nickolas Muray",
    "Ragnar Axelsson",
    "Darogha Ubbas Alli",
    "Ritam Banerjee",
    "Subhankar Banerjee",
    "Pablo Bartholomew",
    "Lala Deen Dayal",
    "Dhaval Dhairyawan",
    "Atul Kasbekar",
    "Yatin Patel",
    "Altaf Qadri",
    "Raghu Rai",
    "Dabboo Ratnani",
    "Benu Sen",
    "Raghubir Singh",
    "Kassian Cephas",
    "Kevin Abosch",
    "Maeve Berry",
    "Bob Carlos Clarke",
    "Richard Mosse",
    "Micha Bar-Am",
    "Rafael Ben-Ari",
    "Nadav Kander",
    "Ziv Koren",
    "Alex Levac",
    "Fratelli Alinari",
    "Olivo Barbieri",
    "Antonio Beato",
    "Felice Beato",
    "Giacomo Brogi",
    "Romano Cagnoni",
    "Ilario Carposio",
    "Elio Ciol",
    "Yvonne De Rosa",
    "Adolfo Farsari",
    "Franco Fontana",
    "Piero Gemelli",
    "Luigi Ghirri",
    "Mario Giacomelli",
    "Mimmo Jodice",
    "Fosco Maraini",
    "Enrico Martino",
    "Tina Modotti",
    "Ugo Mulas",
    "Dianora Niccolini",
    "Giuseppe Palmas",
    "Dino Pedriali",
    "Secondo Pia",
    "Felice Quinto",
    "Vittorio Sella",
    "Frederick Sommer",
    "Oliviero Toscani",
    "Luigi Veronesi",
    "Massimo Vitali",
    "Ester Anderson",
    "Tadasuke Akiyama",
    "Takashi Amano",
    "Nobuyoshi Araki",
    "Taku Aramasa",
    "Taiji Arita",
    "Teisuke Chiba",
    "Ken Domon",
    "Ei-Q",
    "T. Enami",
    "Hakuyō Fuchikami",
    "Mitsutarō Fuku",
    "Katsuji Fukuda",
    "Rosō Fukuhara",
    "Shinzō Fukuhara",
    "Masao Gozu",
    "Mikiko Hara",
    "Tadahiko Hayashi",
    "Takanobu Hayashi",
    "Terushichi Hirai",
    "Horie Kuwajirō",
    "Masao Horino",
    "Tetsuya Ichimura",
    "Seiryū Inoue",
    "Taikichi Irie",
    "Mitsuaki Iwagō",
    "Takeji Iwamiya",
    "Bishin Jumonji",
    "Kameya Tokujirō",
    "Rinko Kawauchi",
    "Seiki Kayamori",
    "Kensuke Kazama",
    "Takashi Kijima",
    "Hiroh Kikai",
    "Shunkichi Kikuchi",
    "Ihei Kimura",
    "Genzō Kitazumi",
    "Fusako Kodama",
    "Kiyoshi Koishi",
    "Akira Komoto",
    "Tomio Kondō",
    "Motoichi Kumagai",
    "Seiji Kurata",
    "Kusakabe Kimbei",
    "Kineo Kuwabara",
    "Shisei Kuwabara",
    "Maeda Genzō",
    "Shinzo Maeda",
    "Susumu Matsushima",
    "Tōyō Miyatake",
    "Miyazaki Yūhi",
    "Aizō Morikawa",
    "Daidō Moriyama",
    "Shigeichi Nagano",
    "Yasushi Nagao",
    "Ikkō Narahara",
    "Yōnosuke Natori",
    "Kiyoshi Nishiyama",
    "Ogawa Kazumasa",
    "Ogawa Seiyo",
    "Yoshino Ōishi",
    "Takashi Okamura",
    "Kōshirō Onchi",
    "Mitsugu Ōnishi",
    "Chizu Ono",
    "Kei Orihara",
    "Akira Satō",
    "Kōji Satō",
    "Tokihiro Satō",
    "Masato Seto",
    "Noriyoshi Shibata",
    "Bukō Shimizu",
    "Kishin Shinoyama",
    "Mieko Shiomi",
    "Issei Suda",
    "Hiroshi Sugimoto",
    "Kaietsu Takagi",
    "Yutaka Takanashi",
    "Masataka Takayama",
    "Tamamura Kozaburō",
    "Akihide Tamura",
    "Sakae Tamura",
    "Sakae Tamura",
    "Shigeru Tamura",
    "Kōtarō Tanaka",
    "Toyoko Tokiwa",
    "Shōmei Tōmatsu",
    "Tomishige Rihei",
    "Akira Toriyama",
    "Uchida Kuichi",
    "Shōji Ueda",
    "Noboru Ueki",
    "Ueno Hikoma",
    "Ukai Gyokusen",
    "Kaoru Usui",
    "Hiroshi Watanabe",
    "Kansuke Yamamoto",
    "Hiroshi Yamazaki",
    "Nakaji Yasui",
    "Yokoyama Matsusaburō",
    "Kohei Yoshiyuki",
    "Mohamed Amin",
    "Priya Ramrakha",
    "Philippe Halsman",
    "Nadim Asfar",
    "Gregory Buchakjian",
    "Izis Bidermanas",
    "Vytautas Stanionis",
    "Kęstutis Stoškus",
    "Antanas Sutkus",
    "Stanislovas Žvirgždas",
    "Mark Divo",
    "Marianne Majerus",
    "Alioune Bâ",
    "Seydou Keïta",
    "Malick Sidibé",
    "Lola Álvarez Bravo",
    "Manuel Álvarez Bravo",
    "Edgar de Evia",
    "Sergio Dorantes",
    "Enrique Metinides",
    "Antonio Olmos",
    "Rubén Ortiz Torres",
    "Hans Aarsman",
    "Emmy Andriesse",
    "Iwan Baan",
    "Henze Boekhout",
    "Anton Corbijn",
    "Rineke Dijkstra",
    "Ed van der Elsken",
    "Karl Hammer",
    "Carli Hermès",
    "Rob Hornstra",
    "Ad Konings",
    "Jeroen Kramer",
    "Inez van Lamsweerde",
    "Frans Lanting",
    "Erwin Olaf",
    "Rahi Rezvani",
    "José Manuel Rodrigues",
    "Levi van Veluw",
    "Laurence Aberhart",
    "Mark Adams",
    "Brian Brake",
    "Peter Bush",
    "Rosaline Margaret Frank",
    "Marti Friedlander",
    "Anne Geddes",
    "Geoff Moon",
    "Robin Morrison",
    "Ans Westra",
    "Herzekiah Andrew Shanu",
    "Rolf Aamot",
    "Jonas Bendiksen",
    "Catherine Cameron",
    "Frode Fjerdingstad",
    "Petter Hegre",
    "Luca Kleve-Ruud",
    "Severin Worm-Petersen",
    "Mobeen Ansari",
    "Tapu Javeri",
    "Adnan Kandhar",
    "Sadia Khan",
    "Farah Mahbub",
    "Huma Mulji",
    "Zaigham Zaidi",
    "Karimeh Abbud",
    "Yousef Khanfar",
    "Khalil Raad",
    "José Luis Rodríguez Pittí",
    "Martín Chambi",
    "Mario Testino",
    "Jan Bułhak",
    "Maciej Dakowicz",
    "Zbigniew Dłubak",
    "Eugeniusz Lokajski",
    "Michal Martychowiec",
    "Kazimierz Nowak",
    "Włodzimierz Puchalski",
    "David Seymour",
    "Stanisław Ignacy Witkiewicz",
    "Casimir Zagourski",
    "Daniel Blaufuks",
    "José Manuel Rodrigues",
    "Helena Almeida",
    "Ioan Mihai Cochinescu",
    "Alexey Brodovich",
    "George Hoyningen-Huene",
    "Yevgeny Khaldei",
    "Rafail Sergeevich Levitsky",
    "Sergei Lvovich Levitsky",
    "El Lissitzky",
    "Gueorgui Pinkhassov",
    "Sergei Mikhailovich Prokudin-Gorskii",
    "Alexander Rodchenko",
    "Natalia Skobeeva",
    "Nicolas Tikhomiroff",
    "Alexey Titarenko",
    "Roman Vishniac",
    "Alphonso Lisk-Carew",
    "John Clang",
    "Teo Bee Yen",
    "Silvia Vaculíková",
    "Marko Modic",
    "Steve Bloom",
    "Kevin Carter",
    "Ernest Cole",
    "Arthur Elliott",
    "David Goldblatt",
    "Bob Gosani",
    "Robert Hamblin",
    "Sam Haskins",
    "Pieter Hugo",
    "Alf Kumalo",
    "David Lurie",
    "Peter Magubane",
    "Michael Meyersfeld",
    "Eric Miller",
    "Santu Mofokeng",
    "Billy Monk",
    "Henrik Purienne",
    "Jürgen Schadeberg",
    "Mikhael Subotzky",
    "Guy Tillim",
    "Gisèle Wulfsohn",
    "Rogelio Bernal Andreo",
    "Francisco Boix",
    "Joan Colom",
    "Joan Fontcuberta",
    "Isidoro Gallo",
    "Chema Madoz",
    "Isabel Muñoz",
    "José Ortiz-Echagüe",
    "Cristina García Rodero",
    "Sofia Ahlbom",
    "Ingrid Falk",
    "Victor Hasselblad",
    "Brita Sofia Hesselius",
    "Olof Jarlbro",
    "Jan Töve Johansson",
    "Sune Jonsson",
    "Mattias Klum",
    "Lennart Nilsson",
    "Anders Petersen",
    "Oscar Gustave Rejlander",
    "Hilda Sjölin",
    "Werner Bischof",
    "René Burri",
    "Robert Frank",
    "Alwina Gossauer",
    "Johann Baptist Isenring",
    "Helmar Lerski",
    "Pierre Rossier",
    "Didier Ruef",
    "Roman Signer",
    "Chien-Chi Chang",
    "Chaiya",
    "Ara Güler",
    "Anya Teixeira",
    "William de Wiveleslie Abney",
    "Timothy Allen",
    "Tom Ang",
    "Malcolm Arbuthnot",
    "Fred Archer",
    "Antony Armstrong-Jones, 1st Earl of Snowdon",
    "Anna Atkins",
    "Gerry Badger",
    "David Bailey",
    "Shirley Baker",
    "Nigel Barker",
    "Lisa Barnard",
    "Emma Barton",
    "Alexander Bassano",
    "Richard Beard",
    "Cecil Beaton",
    "Francis Bedford",
    "George Beldam",
    "Harry Benson",
    "Herbert Bowyer Berkeley",
    "Richard Billingham",
    "J. R. Black",
    "John Blakemore",
    "Dorothy Bohm",
    "Samuel Bourne",
    "Jane Bown",
    "Tony Boxall",
    "Alex Boyd",
    "Bill Brandt",
    "Zana Briski",
    "Hamish Brown",
    "Marc Bryan-Brown",
    "John Bulmer",
    "Victor Burgin",
    "Larry Burrows",
    "Harry Burton",
    "Michael Busselle",
    "Pogus Caesar",
    "Julia Margaret Cameron",
    "William Carrick",
    "Lewis Carroll",
    "Andrew Catlin",
    "Hugh Cecil",
    "Allan Chappelow",
    "William Clarridge",
    "Henry Collen",
    "Joe Cornish",
    "Ron Davies",
    "George Davison",
    "Corinne Day",
    "Peter Dazeley",
    "John Deakin",
    "Peter Dench",
    "Hugh Welch Diamond",
    "Terence Donovan",
    "W. & D. Downey",
    "Gerald Drucker",
    "Peter Henry Emerson",
    "Frederick H. Evans",
    "Jason Evans",
    "Candice Farmer",
    "Roger Fenton",
    "Graham Finlayson",
    "Anna Fox",
    "Stuart Franklin",
    "Peter Fraser",
    "John French",
    "Francis Frith",
    "Peter Wickens Fry",
    "Jill Furmanovsky",
    "Adam Fuss",
    "Alexander Gardner",
    "George Georgiou",
    "Paula Rae Gibson",
    "Fay Godwin",
    "Andy Goldsworthy",
    "Paul Graham",
    "Ken Grant",
    "Ross Halfin",
    "E.R. Hall",
    "David Hamilton",
    "Bert Hardy",
    "Sam Haskins",
    "William Hayes",
    "Darren Heath",
    "Tim Hetherington",
    "David Octavius Hill",
    "Alfred Horsley Hinton",
    "David Hockney",
    "Thomas Hodges",
    "Frederick Hollyer",
    "Eric Hosking",
    "Robert Howlett",
    "David Hurn",
    "William H. Illingworth",
    "Bill Jackson",
    "Anthony Jones",
    "Charles Jones",
    "Philip Jones Griffiths",
    "Michael Kenna",
    "James Kenny",
    "Chris Killip",
    "William Umpleby Kirk",
    "Gary Knight",
    "Nick Knight",
    "Penny Lancaster",
    "Jim Lee",
    "Patrick Lichfield",
    "Iain MacMillan",
    "Simon Marsden",
    "Alfred Maudslay",
    "John Jabez Edwin Mayall",
    "Roger Mayne",
    "Angus McBean",
    "Linda McCartney",
    "Mary McCartney",
    "John McCosh",
    "Don McCullin",
    "Dave McKean",
    "Joseph McKeown",
    "Wendy McMurdo",
    "John McMurtrie",
    "Daniel Meadows",
    "Donald Mennie",
    "Mert and Marcus",
    "Derry Moore, 12th Earl of Drogheda",
    "Raymond Moore",
    "Eadweard Muybridge",
    "Graham Nash",
    "Jimmy Nelson",
    "William Notman",
    "Stephens Orr",
    "Graham Ovenden",
    "Tim Page",
    "Frederick Christian Palmer",
    "John Eastman Palmer",
    "William Eastman Palmer & Sons",
    "John Papillon",
    "Richard Pare",
    "Steve Parish",
    "Norman Parkinson",
    "Martin Parr",
    "Mark Power",
    "Rankin",
    "Tony Ray-Jones",
    "Paul Reas",
    "David Redfern",
    "Sophy Rickett",
    "Simon Roberts",
    "Grace Robertson",
    "James Robertson",
    "Ziki Robertson",
    "Henry Peach Robinson",
    "George Rodger",
    "Horatio Ross",
    "Mary Rosse",
    "Dominic Rouse",
    "William Saunders",
    "Charles Roscoe Savage",
    "Charles Settrington",
    "Charles Shepherd",
    "Victor Sloan",
    "Edwin Smith",
    "Graham Smith",
    "Pennie Smith",
    "Humphrey Spender",
    "Chris Steele-Perkins",
    "David Stewart",
    "John Stezaker",
    "Francis Meadow Sutcliffe",
    "Homer Sykes",
    "Nik Szymanek",
    "William Fox Talbot",
    "Henry Taunt",
    "Sam Taylor-Wood",
    "John Thomson",
    "Marcus Tomlinson",
    "John Topham",
    "Linnaeus Tripe",
    "Nick Turpin",
    "James Valentine",
    "Nick Waplington",
    "Patrick Ward",
    "Allan Warren",
    "Albert Watson",
    "George Washington Wilson",
    "Minnie Weisz",
    '"John Muir Wood"',
    "Walter B. Woodbury",
    "Donovan Wylie",
    "Lorna Yabsley",
    "Yevonde",
    "Paul Yule",
    "Jules Aarons",
    "Slim Aarons",
    "Berenice Abbott",
    "Sam Abell",
    "George W. Ackerman",
    "Ansel Adams",
    "Eddie Adams",
    "Robert Adams",
    "Alfred Shea Addis",
    "Peter van Agtmael",
    "Cris Alexander",
    "Jules T. Allen",
    "Jane Fulton Alt",
    "Stephen Alvarez",
    "Kalliope Amorphous",
    "Evan Amos",
    "George Edward Anderson",
    "Blake Andrews",
    "Allan Arbus",
    "Amy Arbus",
    "Diane Arbus",
    "David Armstrong",
    "Eve Arnold",
    "Bill Aron",
    "Abraham Aronow",
    "Bill Atkinson",
    "Richard Avedon",
    "Jerry Avenaim",
    "Chapman Baehler",
    "John Baldessari",
    "Jamie Baldridge",
    "Lewis Baltz",
    "Tina Barney",
    "William A. Barnhill",
    "George Barris",
    "Pinky Bass",
    "Peter Hill Beard",
    "Carol Beckwith",
    "Lawrence Beitler",
    "Charles Belden",
    "William Bell",
    "E. J. Bellocq",
    "Robert Benecke",
    "Berry Berenson",
    "Andrew D. Bernstein",
    "James Bidgood",
    "Edward Bierstadt",
    "Jack Birns",
    "Erwin Blumenfeld",
    "A. Aubrey Bodine",
    "Christopher Boffoli",
    "Skip Bolen",
    "Phil Borges",
    "Jack E. Boucher",
    "Alice Boughton",
    "Margaret Bourke-White",
    "Mathew Brady",
    "Jim Brandenburg",
    "Marilyn Bridges",
    "Anne Brigman",
    "Mike Brodie",
    "Dan Budnik",
    "Henry Buehman",
    "Wynn Bullock",
    "Christopher Burkett",
    "Harry Callahan",
    "Loren Cameron",
    "Lana Z Caplan",
    "Paul Caponigro",
    "Christopher Capozziello",
    "David Carol",
    "Keith Carter",
    "Kyle Cassidy",
    "Dean Chamberlain",
    "Polly Chandler",
    "Dickey Chapelle",
    "Sarah Charlesworth",
    "William Christenberry",
    "Larry Clark",
    "William Claxton",
    "Charles Clegg",
    "Alvin Langdon Coburn",
    "Lois Conner",
    "Linda Connor",
    "Martha Cooper",
    "Kate Cordsen",
    "Jeff Cowen",
    "Gregory Crewdson",
    "Ted Croner",
    "Imogen Cunningham",
    "Asahel Curtis",
    "Edward S. Curtis",
    "Louise Dahl-Wolfe",
    "Joseph Dankowski",
    "Bruce Davidson",
    "Daniel Davis Jr.",
    "F. Holland Day",
    "Autumn de Wilde",
    "Joe Deal",
    "Loomis Dean",
    "Roy DeCarava",
    "Terry Deglau",
    "Jack Delano",
    "Philip-Lorca diCorcia",
    "John Dominis",
    "Don Donaghy",
    "David Doubilet",
    "Carolyn Drake",
    "Richard Drew",
    "Doug DuBois",
    "Jeff Dunas",
    "David Douglas Duncan",
    "Aimé Dupont",
    "Dutton & Michaels",
    "Charles C. Ebbets",
    "Harold Eugene Edgerton",
    "Hugh Edwards",
    "John Paul Edwards",
    "William Eggleston",
    "Rudolf Eickemeyer Jr.",
    "Alfred Eisenstaedt",
    "Jill Enfield",
    "Clay Enos",
    "Mitch Epstein",
    "Elliott Erwitt",
    "Dulah Marie Evans",
    "Walker Evans",
    "Dennis H. Farber",
    "Chris Faust",
    "James Fee",
    "Andreas Feininger",
    "Mark Feldstein",
    "George Fiske",
    "Sean Flynn",
    "Felice Frankel",
    "Thomas E. Franklin",
    "Leonard Freed",
    "Adrienne French",
    "Arny Freytag",
    "Lee Friedlander",
    "Eva Fuka",
    "Ron Galella",
    "Harry Gamboa Jr.",
    "William Garnett",
    "Arnold Genthe",
    "Ralph Gibson",
    "Carl Giers",
    "Bruce Gilden",
    "Guy Gillette",
    "Steve Giovinco",
    "Barbara Gluck",
    "Frank Gohlke",
    "Anthony Goicolea",
    "Jim Goldberg",
    "Nan Goldin",
    "Rolando Gomez",
    "Greg Gorman",
    "John Gossage",
    "William P. Gottlieb",
    "Hal Gould",
    "Emmet Gowin",
    "Karen Graffeo",
    "Katy Grannan",
    "Herb Greene",
    "Jill Greenberg",
    "Lauren Greenfield",
    "Lois Greenfield",
    "Timothy Greenfield-Sanders",
    "Stan Grossfeld",
    "Bob Gruen",
    "Mark Robert Halper",
    "Dirck Halstead",
    "John R. Hamilton",
    "Adelaide Hanscom",
    "Charles Harbutt",
    "Ron Harris",
    "Alfred A. Hart",
    "David Alan Harvey",
    "Ron Haviv",
    "Masumi Hayashi",
    "Frank Jay Haynes",
    "William Heick",
    "J Malan Heslop",
    "Todd Hido",
    "John K. Hillers",
    "David Hilliard",
    "Lewis Hine",
    "Hiro",
    "John Hoagland",
    "David Hobby",
    "Joseph Holmes",
    "Douglas Hopkins",
    "Horst P. Horst",
    "Charles Howard",
    "Fred Hultstrand",
    "William Hundley",
    "Art Hupy",
    "George Hurrell",
    "Philip Hyde",
    "Jerry Interval",
    "Walter Iooss",
    "Edith Irvine",
    "Lee Isaacs",
    "Yasuhiro Ishimoto",
    "William Henry Jackson",
    "Belle Johnson",
    "Alfred Cheney Johnston",
    "John S. Johnston",
    "Pirkle Jones",
    "Consuelo Kanaga",
    "Gertrude Käsebier",
    "Emy Kat",
    "Mary Morgan Keipp",
    "David Michael Kennedy",
    "Mitch Kern",
    "Robert Glenn Ketchum",
    "Miru Kim",
    "Darius Kinsey",
    "William Klein",
    "Russell Klika",
    "Stuart Klipper",
    "Joseph Knaffl",
    "Karen Knorr",
    "Antonin Kratochvil",
    "George Krause",
    "Ed Krebs",
    "Barbara Kruger",
    "Yasuo Kuniyoshi",
    "Justine Kurland",
    "David LaChapelle",
    "Vincent Laforet",
    "Dorothea Lange",
    "Clarence John Laughlin",
    "Shane Lavalette",
    "Alma Lavenson",
    "Lisa Law",
    "Russell Lee",
    "Annie Leibovitz",
    "Neil Leifer",
    "Jacques Leiser",
    "Herman Leonard",
    "Zoe Leonard",
    "Sherrie Levine",
    "David Levinthal",
    "Helen Levitt",
    "Jerome Liebling",
    "Lawrence Denny Lindsley",
    "O. Winston Link",
    "Jacqueline Livingston",
    "Sal Lopes",
    "Rodney Lough Jr.",
    "Jet Lowe",
    "Benjamin Lowy",
    "George Platt Lynes",
    "Danny Lyon",
    "Pirie MacDonald",
    "Vivian Maier",
    "Jay Maisel",
    "Christopher Makos",
    "Steve Mandel",
    "Sally Mann",
    "Jonathan Mannion",
    "Robert Mapplethorpe",
    "Joan Marcus",
    "Ken Marcus",
    "Mary Ellen Mark",
    "Peter B. Martin",
    "Spider Martin",
    "Oscar G. Mason",
    "Margrethe Mather",
    "Gordon Matta-Clark",
    "Annu Palakunnathu Matthew",
    "Kate Matthews",
    "Morton D. May",
    "Brooke Mayo",
    "John McBride",
    "Will McBride",
    "Steve McCurry",
    "Glynnis McDaris",
    "Joe McNally",
    "Laura McPhee",
    "Steven Meisel",
    "Susan Meiselas",
    "Jeff Mermelstein",
    "Joel Meyerowitz",
    "Duane Michals",
    "Fred E. Miller",
    "Lee Miller",
    "Richard Misrach",
    "Daniel S. Mitchell",
    "Charles Moore",
    "Abelardo Morell",
    "Christopher Morris",
    "Wright Morris",
    "William McKenzie Morrison",
    "Stephen Mosher",
    "David Muench",
    "Richard Murrian",
    "Carl Mydans",
    "Clay Myers",
    "James Nachtwey",
    "Billy Name",
    "Arnold Newman",
    "Pipo Nguyen-duy",
    "Nic Nicosia",
    "Nicholas Nixon",
    "Lee Nye",
    "Michael O'Brien",
    "Catherine Opie",
    "Charles O'Rear",
    "Timothy O'Sullivan",
    "Kevin Ou",
    "Paul Outerbridge",
    "Bill Owens",
    "Robert ParkeHarrison",
    "Gordon Parks",
    "Christian Patterson",
    "Irving Penn",
    "Lucian Perkins",
    "John Pezzenti",
    "John Pfahl",
    "Jack Pierson",
    "Sylvia Plachy",
    "David Plowden",
    "Eliot Porter",
    "Victor Prevost",
    "Hal Prewitt",
    "Richard Prince",
    "Andrew Prokos",
    "Melanie Pullen",
    "Gerald P. Pulley",
    "Herbert Randall",
    "Paul Raphaelson",
    "William H. Rau",
    "Man Ray",
    "Ryan Spencer Reed",
    "H. Reid",
    "Lorne Resnick",
    "Michael Richard",
    "Eugene Richards",
    "Terry Richardson",
    "Robert Riger",
    "Frank Rinehart",
    "Herb Ritts",
    "Manuel Rivera-Ortiz",
    "James Roark",
    "Ruth Robertson",
    "John V. Robinson",
    "Thomas C. Roche",
    "Milton Rogovin",
    "Matthew Rolston",
    "Ben Rose",
    "Barbara Rosenthal",
    "Joe Rosenthal",
    "Martha Rosler",
    "Arthur Rothstein",
    "Galen Rowell",
    "Johnny Rozsa",
    "Andrew J. Russell",
    "Arnold E. Samuelson",
    "Joel Sartore",
    "Francesco Scavullo",
    "Rocky Schenck",
    "T. M. Schleier",
    "Bill Schwab",
    "John Schwartz",
    "Arthur E. Scott",
    "Allan Sekula",
    "Mark Seliger",
    "Andres Serrano",
    "John Sexton",
    "Jamel Shabazz",
    "Charles Sheeler",
    "Bob Shell",
    "Cindy Sherman",
    "Stewart Shining",
    "Stephen Shore",
    "Julius Shulman",
    "John Shuptrine",
    "Marilyn Silverstone",
    "Lorna Simpson",
    "Aaron Siskind",
    "Sandy Skoglund",
    "Neal Slavin",
    "Moneta Sleet Jr.",
    "Henry Holmes Smith",
    "Mickey Smith",
    "Rodney Smith",
    "W. Eugene Smith",
    "Rick Smolan",
    "Melvin Sokolsky",
    "Alec Soth",
    "Pete Souza",
    "Melissa Springer",
    "John Stanmeyer",
    "Edward Steichen",
    "Ralph Steiner",
    "Joel Sternfeld",
    "Louis Stettner",
    "Alfred Stieglitz",
    "Nellie Stockbridge",
    "Ezra Stoller",
    "Dana Stone",
    "Les Stone",
    "Tom Stone",
    "Paul Strand",
    "Zoe Strauss",
    "Roy Stuart",
    "Jock Sturges",
    "Anthony Suau",
    "Kenneth Dupee Swan",
    "John Szarkowski",
    "I. W. Taber",
    "Paulette Tavormina",
    "John Bigelow Taylor",
    "Maggie Taylor",
    "Joyce Tenneson",
    "Warren T. Thompson",
    "George Tice",
    "Barbara Traub",
    "Bill Travis",
    "Eric Treacy",
    "Arthur Tress",
    "John Trobaugh",
    "Thomas Tulis",
    "Spencer Tunick",
    "David C. Turnley",
    "Peter Turnley",
    "Jerry Uelsmann",
    "Doris Ulmann",
    "Brian Ulrich",
    "Steven Underhill",
    "John Vachon",
    "Max Vadukul",
    "James Van Der Zee",
    "Carl Van Vechten",
    "Kathy Vargas",
    "Salvatore Vasapolli",
    "John Veltri",
    "Kiino Villand",
    "William George Wadman",
    "Bob Walker",
    "Andy Warhol",
    "Marion E. Warren",
    "Waswo X. Waswo",
    "Carleton Watkins",
    "Bruce Weber",
    "Weegee",
    "Carrie Mae Weems",
    "William Wegman",
    "Eudora Welty",
    "Henry Wessel Jr.",
    "Brett Weston",
    "Cole Weston",
    "Edward Weston",
    "Kim Weston",
    "John H. White",
    "Minor White",
    "Jeff Widener",
    "Leigh Wiener",
    "Hannah Wilke",
    "Christopher Williams",
    "Michael Williamson",
    "Deborah Willis",
    "Ben Willmore",
    "Bob Willoughby",
    "Laura Wilson",
    "Kathryn Tucker Windham",
    "Garry Winogrand",
    "Ernest Withers",
    "Joel-Peter Witkin",
    "Marion Post Wolcott",
    "Art Wolfe",
    "Francesca Woodman",
    "Don Worth",
    "Max Yavno",
    "Bunny Yeager",
    "Jerome Zerbe",
    "John G. Zimmerman",
    "David Drew Zingg",
    "Fred Zinn",
    "Monte Zucker",
    "Alejandro López de Haro",
    "Ricardo Gómez Pérez",
    "Huynh Cong Ut",
    "Zohra Bensemra",
    "Sara Facio",
    "Annemarie Heinrich",
    "Adriana Lestido",
    "Grete Stern",
    "Narelle Autio",
    "Polly Borland",
    "June Browne",
    "Alex Cearns",
    "Olive Cotton",
    "Maggie Diaz",
    "Joyce Evans",
    "Anne Geddes",
    "Kate Geraghty",
    "Carol Jerrems",
    "Tracey Moffatt",
    "Polixeni Papapetrou",
    "Alexia Sinclair",
    "Ruby Spowart",
    "Claire Beck",
    "Gerti Deutsch",
    "Trude Fleischmann",
    "Dora Kallmus",
    "Lotte Meitner-Graf",
    "Inge Morath",
    "Margherita Spiluttini",
    "Edith Tudor-Hart",
    "Rena Effendi",
    "Marleen Daniels",
    "Martine Franck",
    "Germaine Van Parys",
    "Eva Vermandel",
    "Angèle Etoundi Essamba",
    "Vikky Alexander",
    "Raymonde April",
    "Reva Brooks",
    "Geneviève Cadieux",
    "Petra Collins",
    "Nathalie Daoust",
    "Millie Gamble",
    "Jill Greenberg",
    "Heidi Hollinger",
    "Laura Letinsky",
    "Lorraine Monk",
    "Geraldine Moodie",
    "Julie Moos",
    "Nina Raginsky",
    "Clara Sipprell",
    "Margaret Watkins",
    "Chen Man",
    "Hou Bo",
    "Shao Hua",
    "O Zhang",
    "Zhang Jingna",
    "Sanja Iveković",
    "Marta María Pérez Bravo",
    "Lissette Solorzano",
    "Veronika Bromová",
    "Markéta Luskačová",
    "Emila Medková",
    "Lucia Moholy",
    "Marie Šechtlová",
    "Jette Bang",
    "Sisse Brimberg",
    "Helena Christensen",
    "Frederikke Federspiel",
    "Marianne Grøndahl",
    "Thora Hallager",
    "Johanne Hesbeck",
    "Kirsten Klein",
    "Astrid Kruse Jensen",
    "Julie Laurberg",
    "Rigmor Mydtskov",
    "Mary Steen",
    "Mary Willumsen",
    "Benedicte Wrensted",
    "Ann Tenno",
    "Eija-Liisa Ahtila",
    "Nanna Hänninen",
    "Sirkka-Liisa Konttinen",
    "Susanna Majuri",
    "Martine Barrat",
    "Claude Batho",
    "Valérie Belin",
    "Alexandra Boulat",
    "Claude Cahun",
    "Sophie Calle",
    "Dominique Darbois",
    "Françoise Demulder",
    "Geneviève Élisabeth Disdéri",
    "Claudine Doury",
    "Gisèle Freund",
    "Laure Albin Guillot",
    "Florence Henri",
    "Irina Ionesco",
    "Germaine Krull",
    "Brigitte Lacombe",
    "Catherine Leroy",
    "Benedicte Van der Maar",
    "Dora Maar",
    "Sarah Moon",
    "Janine Niépce",
    "Bettina Rheims",
    "Sophie Ristelhueber",
    "Emmanuelle Riva",
    "Lise Sarfati",
    "Stéphane Sednaoui",
    "Christine Spengler",
    "Agnès Varda",
    "Véronique de Viguerie",
    "Gertrud Arndt",
    "Uta Barth",
    "Ingeborg de Beausacq",
    "Hilla Becher",
    "Sibylle Bergemann",
    "Emilie Bieber",
    "Aenne Biermann",
    "Ilse Bing",
    "Anna Blume",
    "Marianne Breslauer",
    "Frauke Eigen",
    "Marie Goslich",
    "Roswitha Hecke",
    "Lotte Herrlich",
    "Hannah Höch",
    "Candida Höfer",
    "Lotte Jacobi",
    "Astrid Kirchherr",
    "Erna Lendvai-Dircksen",
    "Esther Levine",
    "Loretta Lux",
    "Rut Blees Luxemburg",
    "Melanie Manchot",
    "Hedda Morrison",
    "Anja Niedringhaus",
    "Margret Nissen",
    "Anne-Katrin Purkiss",
    "Katja Rahlwes",
    "Ursula Richter",
    "Leni Riefenstahl",
    "Frieda Riess",
    "Stefanie Schneider",
    "Ursula Schulz-Dornburg",
    "Katharina Sieverding",
    "Annegret Soltau",
    "Gerda Taro",
    "Ellen von Unwerth",
    "Bertha Wehnert-Beckmann",
    "Ianna Andreadis",
    "Nelly's",
    "Mary Paraskeva",
    "Athena Tacha",
    "María Cristina Orive",
    "Wong Wo Bik",
    "Vivienne Balla",
    "Ergy Landau",
    "Rebekka Guðleifsdóttir",
    "Pamella Bordes",
    "Indrani",
    "Saadiya Kochar",
    "Dayanita Singh",
    "Sooni Taraporevala",
    "Homai Vyarawalla",
    "Parisa Damandan",
    "Shadi Ghadirian",
    "Zahra Kazemi",
    "Sanaz Mazinani",
    "Shirin Neshat",
    "Shirana Shahbazi",
    "Mitra Tabrizian",
    "Newsha Tavakolian",
    "Maryam Zandi",
    "Liselotte Grschebina",
    "Letizia Battaglia",
    "Vanessa Beecroft",
    "Yvonne De Rosa",
    "Tina Modotti",
    "Dianora Niccolini",
    "Virginia Oldoini",
    "Floria Sigismondi",
    "Esther Anderson",
    "Mikiko Hara",
    "Hiromix",
    "Hisae Imai",
    "Miyako Ishiuchi",
    "Fusako Kodama",
    "Michiko Kon",
    "Miyuki Matsuda",
    "Michiko Matsumoto",
    "Yurie Nagashima",
    "Mika Ninagawa",
    "Rika Noguchi",
    "Yoshino Ōishi",
    "Yuki Onodera",
    "Kei Orihara",
    "Tsuneko Sasamoto",
    "Shima Ryū",
    "Mieko Shiomi",
    "Kunié Sugiura",
    "Cozue Takagi",
    "Toyoko Tokiwa",
    "Eiko Yamazawa",
    "Miwa Yanagi",
    "Ruiko Yoshida",
    "Inta Ruka",
    "Esther Shalev-Gerz",
    "Audronė Vaupšienė",
    "Marianne Majerus",
    "Lola Álvarez Bravo",
    "Blanca Charolet",
    "Maya Goded",
    "Lourdes Grobet",
    "Graciela Iturbide",
    "Teresa Margolles",
    "Cristina Goettsch Mittermeier",
    "Dulce Pinzon",
    "Mariana Yampolsky",
    "Emmy Andriesse",
    "Katharina Behrend",
    "Eva Besnyö",
    "Marrie Bot",
    "Rineke Dijkstra",
    "Jacqueline Hassink",
    "Inez van Lamsweerde",
    "Dana Lixenberg",
    "Alexandrine Tinné",
    "New Zealand",
    "Suzanna Clarke",
    "Eileen Olive Deste",
    "Amy Merania Harper",
    "Alyson Hunter",
    "Thelma Rene Kent",
    "Elizabeth Pulman",
    "Jane Ussher",
    "Ans Westra",
    "Catherine Cameron",
    "Anne Helene Gjelstad",
    "Elisabeth Meyer",
    "Mimsy Møller",
    "Hanneli Mustaparta",
    "Karimeh Abbud",
    "Sama Raena Alshaibi",
    "Emily Jacir",
    "Ahlam Shibli",
    "Lotte Beese",
    "Margaret Michaelis-Sachs",
    "Nata Piaskowski",
    "Faye Schulman",
    "Alexandra Croitoru",
    "Lena Herzog",
    "Ida Kar",
    "Diana Markosian",
    "Vera Elkan",
    "Constance Stuart Larrabee",
    "Zanele Muholi",
    "Colla Swart",
    "Gisèle Wulfsohn",
    "Nikki S. Lee",
    "Cristina García Rodero",
    "Cristina Martín Lara",
    "Ouka Leele",
    "Isabel Muñoz",
    "Cristina Otero",
    "Sofia Ahlbom",
    "Ingrid Falk",
    "Marianne Greenwood",
    "Brita Sofia Hesselius",
    "Tuija Lindström",
    "Elisabeth Ohlson",
    "Anna Riwkin-Brick",
    "Hilda Sjölin",
    "Bertha Valerius",
    "Hélène Binet",
    "Henriette Grindat",
    "Ella Maillart",
    "Annemarie Schwarzenbach",
    "Semiha Es",
    "Maryam Şahinyan",
    "Elena Filatova",
    "Anya Teixeira",
    "Sarah Angelina Acland",
    "Heather Angel",
    "Anna Atkins",
    "Lisa Barnard",
    "Emma Barton",
    "Dorothy Bohm",
    "Jane Bown",
    "Zana Briski",
    "Christina Broom",
    "Julia Margaret Cameron",
    "Corinne Day",
    "Susan Derges",
    "Mary Dillwyn",
    "Olive Edis",
    "Candice Farmer",
    "Mary Georgina Filmer",
    "Mary Fitzpatrick",
    "Anna Fox",
    "Constance Fox Talbot",
    "Paula Rae Gibson",
    "Fay Godwin",
    "Clementina Hawarden",
    "Alice Hughes",
    "Elsbeth Juda",
    "Etheldreda Laing",
    "Mary McCartney",
    "Wendy McMurdo",
    "Lotte Meitner-Graf",
    "Caroline Emily Nevill",
    "Laura Pannack",
    "Suze Randall",
    "Sophy Rickett",
    "Grace Robertson",
    "Mary Rosse",
    "Jane Martha St. John",
    "Pennie Smith",
    "Jo Spence",
    "Hannah Starkey",
    "Sam Taylor-Wood",
    "Agnes Warburg",
    "Gillian Wearing",
    "Jane Wigley",
    "Vanessa Winship",
    "Catherine Yass",
    "Madame Yevonde",
    "Kathryn Abbe",
    "Berenice Abbott",
    "Harriet Chalmers Adams",
    "Marian Hooper Adams",
    "Lynsey Addario",
    "Laura Aguilar",
    "Jane Fulton Alt",
    "Nancy Lee Andrews",
    "Eleanor Antin",
    "Amy Arbus",
    "Diane Arbus",
    "Laura Adams Armer",
    "Eve Arnold",
    "Kristen Ashburn",
    "Jane Evelyn Atwood",
    "Ellen Auerbach",
    "Alice Austen",
    "Elizabeth Axtman",
    "Catharine Weed Barnes",
    "Tina Barney",
    "Ruth-Marion Baruch",
    "Lillian Bassman",
    "Jessie Tarbox Beals",
    "Carol Beckwith",
    "Zaida Ben-Yusuf",
    "Lynne Bentley-Kemp",
    "Berry Berenson",
    "Nina Berman",
    "Ruth Bernhard",
    "Ania Bien",
    "Joan E. Biren",
    "Nadine Blacklock",
    "Julie Blackmon",
    "Andrea Blanch",
    "Lucienne Bloch",
    "Gay Block",
    "Debra Bloomfield",
    "Thérèse Bonney",
    "Alice Boughton",
    "Margaret Bourke-White",
    "Louise Arner Boyd",
    "Marilyn Bridges",
    "Anne Brigman",
    "Charlotte Brooks",
    "Ellen Brooks",
    "Kate Brooks",
    "Adrien Broom",
    "Esther Bubley",
    "Elizabeth Buehrmann",
    "Shirley Burman",
    "Eleanor Butler Alexander-Roosevelt",
    "Evelyn Cameron",
    "Marion Carpenter",
    "Elinor Carucci",
    "Dickey Chapelle",
    "Rose Clark",
    "Lynne Cohen",
    "Carolyn Cole",
    "Marjory Collins",
    "Nancy Ford Cones",
    "Lois Conner",
    "Linda Connor",
    "Marjorie Content",
    "Martha Cooper",
    "Kate Cordsen",
    "Tee Corinne",
    "Marie Cosindas",
    "Honey Lee Cottrell",
    "Renée Cox",
    "Imogen Cunningham",
    "Louise Dahl-Wolfe",
    "Judy Dater",
    "Lynn Davis",
    "Mary Devens",
    "Maggie Diaz",
    "Jessica Dimmock",
    "Carolyn Drake",
    "Susan Eakins",
    "Sandra Eisert",
    "Cynthia Elbaum",
    "Jill Enfield",
    "Marion Ettlinger",
    "Emma Justine Farnsworth",
    "Deanne Fitzmaurice",
    "Susan Ford",
    "Mary Lou Foy",
    "Toni Frissell",
    "Eva Fuka",
    "Helen K. Garber",
    "Emme Gerhard",
    "Mayme Gerhard",
    "Wilda Gerideau-Squires",
    "Paola Gianturco",
    "Laura Gilpin",
    "Barbara Gluck",
    "Nan Goldin",
    "Suzy Gorman",
    "Karen Graffeo",
    "Katy Grannan",
    "Beth Green",
    "Jill Greenberg",
    "Lauren Greenfield",
    "Caroline Gurrey",
    "Carol Guzy",
    "Gail Albert Halaban",
    "Masumi Hayashi",
    "Alexandra Hedison",
    "Diana Mara Henry",
    "Lena Herzog",
    "Elizabeth Heyert",
    "Carol M. Highsmith",
    "Martha Holmes",
    "Roni Horn",
    "Edith Irvine",
    "Marcey Jacobson",
    "Belle Johnson",
    "Frances Benjamin Johnston",
    "Sarah Louise Judd",
    "Consuelo Kanaga",
    "Gertrude Käsebier",
    "Emy Kat",
    "Mary Morgan Keipp",
    "Miru Kim",
    "Helen Johns Kirtland",
    "Deborah Copaken Kogan",
    "Barbara Kruger",
    "Justine Kurland",
    "Kay Lahusen",
    "Wendy Sue Lamm",
    "Dorothea Lange",
    "Alma Lavenson",
    "Nina Leen",
    "Adelaide Hanscom Leeson",
    "Annie Leibovitz",
    "Zoe Leonard",
    "Rebecca Lepkoff",
    "Sherrie Levine",
    "Helen Levitt",
    "Jacqueline Livingston",
    "Ruth Harriet Louise",
    "Elizabeth Gill Lui",
    "Vivian Maier",
    "Sally Mann",
    "Malerie Marder",
    "Mary Ellen Mark",
    "Diana Markosian",
    "Margrethe Mather",
    "Rebecca Matlock",
    "Kate Matthews",
    "Dona Ann McAdams",
    "Linda McCartney",
    "Melodie McDaniel",
    "Laura McPhee",
    "Susan Meiselas",
    "Florence Meyer",
    "Hansel Mieth",
    "Lee Miller",
    "Lisette Model",
    "Andrea Modica",
    "Jeannette Montgomery Barron",
    "Barbara Morgan",
    "Lida Moser",
    "Helen Messinger Murdoch",
    "Bea Nettles",
    "Anne Noggle",
    "Dorothy Norman",
    "Catherine Opie",
    "Ruth Orkin",
    "Marvin Breckinridge Patterson",
    "Stacy Pearsall",
    "Sylvia Plachy",
    "Anita Pollitzer",
    "Greta Pratt",
    "Melanie Pullen",
    "Jane Reece",
    "Cherie Roberts",
    "Ruth Robertson",
    "Ann Rosener",
    "Barbara Rosenthal",
    "Louise Rosskam",
    "Marissa Roth",
    "Eva Rubinstein",
    "Liza Ryan",
    "Virginia Schau",
    "Collier Schorr",
    "Sarah Choate Sears",
    "Cindy Sherman",
    "Marilyn Silverstone",
    "Taryn Simon",
    "Lorna Simpson",
    "Sandy Skoglund",
    "Polly Smith",
    "Rosalind Solomon",
    "Melissa Springer",
    "Ellen Stagg",
    "Susan Hacker Stang",
    "Sally Stapleton",
    "Amy Stein",
    "Nellie Stockbridge",
    "Zoe Strauss",
    "Nancy M. Stuart",
    "Rachel Sussman",
    "Maggie Taylor",
    "Joyce Tenneson",
    "Beatrice Tonnesen",
    "Barbara Traub",
    "Mellon Tytell",
    "Doris Ulmann",
    "Penelope Umbrico",
    "Raissa Venables",
    "Ami Vitale",
    "Elizabeth Flint Wade",
    "Eva Watson-Schütze",
    "Carrie Mae Weems",
    "Annie Wells",
    "Eudora Welty",
    "Myra Albert Wiggins",
    "Hannah Wilke",
    "Laura Wilson",
    "Sharon Wohlmuth",
    "Marion Post Wolcott",
    "Linda Wolf",
    "Penny Wolin",
    "Francesca Woodman",
    "Yelena Yemchuk",
    "Umida Akhmedova",
    "Jill Furmanovsky",
    "Suzanna Clarke ",
    "Ingeborg de Beausacq",
    "Flor Garduño",
    "Sandra-Lee Phipps",
    "Ron Jude",
    "Roe Etheridge",
    "Adam Broomberg & Oliver Chanarin",
    "Torbjorn Rodland",
    "Gerry Johanson",
    "Michael Schmidt",
    "photographer unknown",
    "Eikoh Hosoe",
    "Kikuji Kawada",
    "Dirk Braeckman",
    "Trevor Paglen",
    "Masahisa Fukase",
    "Daisuke Yokota",
    "Tod Papageorge",
    "Christopher Anderson",
    "Melissa Catanese",
    "Ed Panar",
    "Mike Slack",
    "Zoe Ghertner",
    "Will Steacy",
    "Wataru Yamamoto",
    "Werner Herzog",
    "Trine Sondergaard",
    "Tim Hyde",
    "Thomas Demand",
    "Terri Weifenbach",
    "Ted Fair",
    "Suzanna Zak",
    "Susan Lipper",
    "Stephen Gill",
    "Stephanie Kiwitt",
    "Sophia Belkin",
    "Shawn Records",
    "Sean Vegezzi",
    "Sean Stewart",
    "Sam Falls",
    "Richard Rothman",
    "Louis Draper",
    "Wayne Lawrence",
    "John Divola",
    "Thomas Roma",
    "Taiyo Onorato & Nico Krebs",
    "Lieko Shiga",
    "Yoshikatsu Fuji",
    "Ute Mahler",
    "Werner Mahler",
    "Cristina de Middel",
    "Henry Horenstein",
    "Arno Rafael Minkkinen"
  ]
